name: Deploy Java Web App to Azure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: first-azure-app-poc  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: /home/runner/work/springboot/springboot # set this to the path to your web app project
  JAVA_VERSION: '1.8'                # set this to the node version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}     # set GH repo secret with the publish profile of the web app
  REGISTRY_LOGIN_SERVER: 'delaysrepo.azurecr.io'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn clean install --file pom.xml
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: delaysrepo.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - run: |
        docker build . -t delaysrepo.azurecr.io/springbootapp:3.0.0
        docker push delaysrepo.azurecr.io/springbootapp:3.0.0
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'delaysrepo.azurecr.io/springbootapp:3.0.0'		
        registry-login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.AZURE_CLIENT_ID }}
        registry-password: ${{ secrets.AZURE_CLIENT_SECRET }}		
